[package]
name = "frontend"
version = "0.1.0"
authors = ["Oliver Schneider <git-no-reply-9879165716479413131@oli-obk.de>"]

[dependencies]
yew = { version = "0.3.0", git = "https://github.com/DenisKolodin/yew.git" }
