language: rust
cache: cargo
rust:
# remember to clear travis caches when updating the nightly version
- nightly-2018-01-20
before_install:
  - rustup component add rls-preview
  - rustup component add rust-src
  - rustup component add rust-analysis
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev # postgresql-9.6
  - cargo install cargo-web
  - rustup target add asmjs-unknown-emscripten
  - cargo install diesel_cli --no-default-features --features postgres
  #- diesel migration run
script:
  - cargo build
notifications:
  email:
    on_success: never
branches:
  only:
  - master
env:
  global:
  - RUST_TEST_NOCAPTURE=1
