language: rust
rust:
- nightly-2018-01-13
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev postgresql-9.6
notifications:
  email:
    on_success: never
branches:
  only:
  - master
env:
  global:
  - RUST_TEST_NOCAPTURE=1
