language: rust
rust:
- nightly-2018-01-13
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev postgresql-9.6
  - cargo install cargo-web
  - rustup target add asmjs-unknown-emscripten
script:
  cargo build
  cd frontend && cargo web build
notifications:
  email:
    on_success: never
branches:
  only:
  - master
env:
  global:
  - RUST_TEST_NOCAPTURE=1
